import {getI18nMessage} from "@addon-core/browser";

import AbstractLocale from "./AbstractLocale";

import {convertLocaleKey, normalizeLocale} from "@locale/utils";

import {Language, LocaleCustomKeyForLanguage, LocaleProvider, LocaleStructure} from "@typing/locale";

export interface LocaleNativeStructure extends LocaleStructure {}

export default class NativeLocale extends AbstractLocale<LocaleNativeStructure> {
    private static instance?: LocaleProvider<LocaleNativeStructure>;

    public static getInstance<S extends LocaleStructure = LocaleNativeStructure>(): LocaleProvider<S> {
        return (NativeLocale.instance ??= new NativeLocale());
    }

    private readonly language?: Language;

    constructor() {
        super();

        const localeLang = getI18nMessage(LocaleCustomKeyForLanguage);
        const lang = normalizeLocale(localeLang);

        if (!lang) {
            console.warn(`Locale Native: Language "${localeLang}" is not supported yet by framework`);
        }

        if (localeLang && lang && localeLang !== lang) {
            console.info(`Locale Native: Instead of "${localeLang}" language, "${lang}" is used`);
        }

        this.language = lang;
    }

    public lang(): Language {
        if (!this.language) {
            throw new Error("Locale Native: Unable to get UI language");
        }

        return this.language;
    }

    public keys(): Set<keyof LocaleNativeStructure> {
        try {
            // @ts-expect-error: __ADNBN_LOCALE_KEYS__ is a virtual variable generated by the bundler `src/cli/plugins/locale/index.ts`
            return new Set<string>(__ADNBN_LOCALE_KEYS__);
        } catch (e) {
            console.error("Locale Native: Unable to get keys", e);

            return new Set<string>();
        }
    }

    public languages(): Set<Language> {
        try {
            // @ts-expect-error: __ADNBN_DEFINED_LOCALES__ is a virtual variable generated by the bundler `src/cli/plugins/locale/index.ts`
            return new Set<Language>(__ADNBN_DEFINED_LOCALES__);
        } catch (e) {
            console.error("Locale Native: Unable to get defined locales", e);

            return new Set<Language>();
        }
    }

    protected value(key: Extract<keyof LocaleNativeStructure, string>): string | undefined {
        const value = getI18nMessage(convertLocaleKey(key));

        if (!value || value.length === 0) {
            return undefined;
        }

        return value;
    }
}
