import {getI18nMessage} from "@addon-core/browser";

import AbstractLocale from "./AbstractLocale";

import {convertLocaleKey, resolveLanguage} from "@locale/utils";

import {Language, LocaleCustomKeyForLanguage, LocaleProvider} from "@typing/locale";

/** Augmented by the generated .adnbn/locale.d.ts for the current app. */
export interface LocaleNativeStructure {}

export default class NativeLocale<S extends object = LocaleNativeStructure> extends AbstractLocale<S> {
    private static instance?: LocaleProvider<LocaleNativeStructure>;

    public static getInstance(): LocaleProvider<LocaleNativeStructure> {
        return (NativeLocale.instance ??= new NativeLocale());
    }

    private readonly language?: Language;

    constructor() {
        super();

        /**
         Locale detection note:
         Chrome does NOT expose an API to get the effective translation locale.
         getUILanguage() returns browser UI language (e.g., es-MX),
         even if extension translations fall back to default_locale (e.g., en).
         To detect the actual language used by i18n, we read a locale marker
         from messages.json via chrome.i18n.getMessage().
         */
        const markerLang = getI18nMessage(LocaleCustomKeyForLanguage);
        const resolvedLang = resolveLanguage(markerLang);

        if (!resolvedLang) {
            console.warn(`[NativeLocale] Unsupported language detected: "${markerLang}".`);
        }

        if (markerLang && resolvedLang && markerLang !== resolvedLang) {
            console.info(`[NativeLocale] Language normalized: using "${resolvedLang}" instead of "${markerLang}".`);
        }

        this.language = resolvedLang;
    }

    public lang(): Language {
        if (!this.language) {
            throw new Error("[NativeLocale] Language is not defined. Failed to determine a supported locale.");
        }

        return this.language;
    }

    public keys(): Set<keyof S> {
        try {
            // @ts-expect-error: __ADNBN_LOCALE_KEYS__ is a virtual variable generated by the bundler `src/cli/plugins/locale/index.ts`
            return new Set<string>(__ADNBN_LOCALE_KEYS__) as Set<keyof S>;
        } catch (e) {
            console.error("[NativeLocale] Failed to access locale keys. Ensure the bundler plugin is active.", e);

            return new Set<keyof S>();
        }
    }

    public languages(): Set<Language> {
        try {
            // @ts-expect-error: __ADNBN_DEFINED_LOCALES__ is a virtual variable generated by the bundler `src/cli/plugins/locale/index.ts`
            return new Set<Language>(__ADNBN_DEFINED_LOCALES__);
        } catch (e) {
            console.error("[NativeLocale] Failed to access defined locales. Check virtual variables configuration.", e);

            return new Set<Language>();
        }
    }

    protected value(key: Extract<keyof S, string>): string | undefined {
        const value = getI18nMessage(convertLocaleKey(key));

        // Native i18n returns an empty string for missing messages too; build keys distinguish valid empty translations.
        if (value === "" && !this.keys().has(key)) {
            return undefined;
        }

        return value;
    }
}
