import {ProxySandbox} from "@sandbox/providers";

import {SandboxDefinition, SandboxParameters, SandboxUnresolvedDefinition} from "@typing/sandbox";
import type {SandboxName, SandboxProxyTarget} from "@sandbox/index";
import type {TransportType} from "@typing/transport";

export * from "@typing/sandbox";

export type SandboxAlias = string;

export type SandboxMap = Map<SandboxAlias, SandboxParameters>;

export const defineSandbox = <T extends TransportType>(options: SandboxDefinition<T>): SandboxDefinition<T> => {
    return options;
};

export const getSandboxes = (): SandboxMap => {
    const sandboxes: SandboxMap = new Map();

    try {
        // @ts-expect-error: __ADNBN_SANDBOX_PARAMETERS__ is a virtual variable generated by the sandbox plugin.
        Object.entries<SandboxParameters>(__ADNBN_SANDBOX_PARAMETERS__).forEach(([key, value]) => {
            sandboxes.set(key, value);
        });
    } catch (e) {
        console.error("Failed getting sandboxes: ", e);
    }

    return sandboxes;
};

export const getSandbox = <N extends SandboxName>(name: N): SandboxProxyTarget<N> => {
    const parameters = getSandboxes().get(name);

    if (!parameters) {
        throw new Error(`Unable to get sandbox: ${name}`);
    }

    return new ProxySandbox(name, parameters).get() as SandboxProxyTarget<N>;
};
